SELECT DISTINCT PP.POLICYNUMBER,II.INSTALLMENTNUMBER,I.INVOICENUMBER,I.EVENTDATE
 FROM BC_INVOICEITEM II
INNER JOIN BC_INVOICE I ON I.ID = II.INVOICEID
INNER JOIN BC_POLICYPERIOD PP ON II.POLICYPERIODID = PP.ID
INNER JOIN BC_POLICY P ON p.id = pp.policyid
INNER JOIN BC_CHARGE C ON C.ID = II.CHARGEID
INNER JOIN BC_BILLINGINSTRUCTION BI ON BI.ID = C.BILLINGINSTRUCTIONID
WHERE II.RETIRED = 0
  AND PP.RETIRED = 0    
  AND BI.SUBTYPE = 5
  AND I.RETIRED = 0
  AND II.INSTALLMENTNUMBER > 1  
  AND I.ENDORSEMENTNUMBER_GCS IS NULL
  AND I.EVENTDATE < GETDATE()-1
  AND PP.CANCELSTATUS <> 3
  AND I.EVENTDATE >= '<month> 00:00:00'
  AND P.LOBCODE = 10004